apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx:1.17.2-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /home/nginx
      name: storage
  volumes:
    - name:  storage
      hostPath:
        path: /workspace
        type: Directory
