apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: nginx-pod
      labels:
        app: web
    spec:
      containers:
      - image: nginx:1.17.2-alpine
        name: nginx-container
